### PR TITLE
#924 - Added support for caching for publick pages in order to reduce…

### PR DESCRIPTION
**Pull request by ceckoslab**
… the number of backend calls when customer visits shop for first time. Adding frontend cookie = guest-customer-session and deleting it when customer reaches non public page. For example product page.

### CODE REVIEW

**Comment by miguelbalparda** [comment]
@ceckoslab can you add some more info about this? Maybe some code comments. I think I understand what do you want to implement but I'm not entirely sure if this is the best way to do it.

**Comment by ceckoslab** [comment]
I added 2 new configuration fields in System -> System -> Configuration -> Varnish Options:

guest caching admin settngs

In current commit  "Guest Caching" is enabled by default. I check in VCL configuration if "Guest Caching" is enabled. If enabled I don't fire Varnish Session Generation. 

Later I do 2 checks:

 * Does customer has NO frontend cookie
 * Is current url NOT part of "Guest Caching Blacklist Url Parts" urls

If those conditions are satisfied then I do:

vcl_recv:
```
set req.http.X-Varnish-Faked-Session = "frontend=guest-customer-session";

if (req.http.Cookie) {
    # client sent us cookies, just not a frontend cookie. try not to blow
    # away the extra cookies
    std.collect(req.http.Cookie);
       set req.http.Cookie = req.http.X-Varnish-Faked-Session +
       "; " + req.http.Cookie;
} else {
       set req.http.Cookie = req.http.X-Varnish-Faked-Session;
}
```

Basically all guest users have cookie frontend=guest-customer-session but if they reach any url from "Guest Caching Blacklist Url Parts" then I unset guest cookie:

vcl_recv:
```
if ({{guest_caching_enable}} &&
    req.http.Cookie ~ "frontend=guest-customer-session" &&
    req.url ~ "({{guest_caching_blacklist}})") {
        unset req.http.Cookie;
        unset req.http.X-Varnish-Faked-Session;
        return (pipe);
}
```

Facts:
 * "Guest Caching" is enabled by default in my current commit
 * So far this is implemented only for Varnish 3.x
 * I designed this in order to handle public visitors on specific pages (home, cms pages, product list)
 * "Guest Caching Blacklist Url Parts" is a list of urls where I need real session and formKey
 * Adding products to cart may not work if for example customer tries to add product from product listing, because this customer may still have cookie frontend=guest-customer-session

I am open for feedback and if somebody could give me second opinion and suggestions to change something in my PR.

**Comment by miguelbalparda** [comment]
@ceckoslab with the latest merges now this code has conflicts. Can you check them? Also I'm seeing you didn't support Varnish 4, can you add support for it?

**Comment by ceckoslab** [comment]
@miguelbalparda I will fix the merge conflicts and will take care about Varnish4. I found another problem during my tests so I am working on it.

**Comment by miguelbalparda** [comment]
Any news on this @ceckoslab?

**Comment by ceckoslab** [comment]
@miguelbalparda I found some problems when I tested with subdomain like local.example.com and I got overloaded with other more important tasks. May be we can close this PR and later I can come back again with better solution.

**Pull request closed without merging**
