### PR TITLE
#963 Fix the Nginx 403 issue with urls which are starting with a dot

### PR DESCRIPTION
**Pull request by andreasemer**
https://github.com/nexcess/magento-turpentine/issues/963 For more info about the issue

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Do you think this will affect in any way other users?

**Comment by andreasemer** [comment]
No, i don't think so. This change will just replace the "." with "_" 
so for example
http://example.com/turpentine/esi/getBlock/method/esi/access/private/ttl/0/hmac/123/data/.qGPQ0YixsP3bFHr
will be
http://example.com/turpentine/esi/getBlock/method/esi/access/private/ttl/0/hmac/123/data/_qGPQ0YixsP3bFHr

and 99% of the Nginx webservsers (403ing hidden files is almost a default config) don´t think that the requested files are hidden.

**Comment by andreasemer** [comment]
Any more questions? Is there something why this should be not mergend? We are using this since several weeks without problems...

**Comment by sebastianwahn** [comment]
I also applied the hotfix locally. Works like a charm since.

**Comment by miguelbalparda** [comment]
Merged, thank you for the help!

**Pull request merged**
