### PR TITLE
Implemented Load Balancing Support

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
Implemented round-robin load-balancing support via Magento configuration. Varnish will divide load among multiple web servers, and can also check if they are up via a probe URL.
Sponsored by Kega (@itnova).

### CODE REVIEW

**Comment by jeroenvermeulen** [comment]
@aheadley Have you looked at this PR already?

**Comment by aheadley** [comment]
@jeroenvermeulen I'm no longer working for Nexcess so it's not up to me. I'm not sure who is taking over the project unfortunately.

**Comment by jeroenvermeulen** [comment]
@miguelbalparda @aricwatson Do you want me to re-submit this PR with the merge conflicts solved?
At the time I submitted it there were no conflicts, but it has been on the shelf for a while.

**Comment by miguelbalparda** [comment]
@jeroenvermeulen it will be really helpful! I checked this PR yesterday and I think this is a great addition to the module, once you submit the new PR I will merge it right away.

**Comment by jeroenvermeulen** [comment]
I merged the current `devel` branch and solved the conflict, which was only comments.
Now my PR can be merged.
I see Travis CI fails, but it looks like that's not my fault, am I right?

**Comment by jeroenvermeulen** [comment]
I will close this PR, the changes do not look right.
I will resubmit.

**Comment by miguelbalparda** [comment]
@jeroenvermeulen TravisCI is failing because we are waiting for some dependencies to be whitelisted in their new system, definitely not your fault. Feel free to resubmit your PR.

**Pull request closed without merging**
