### PR TITLE
Varnish4 compat

### PR DESCRIPTION
**Pull request by eth8505**
Add varnish4 compatibility to turpentine.
Note: I have completely refactored the varnish version auto-detection.

### CODE REVIEW

**Comment by craigcarnell** [comment]
@aheadley Any updates on Varnish 4 support? Thanks

**Comment by eth8505** [comment]
Just to let everyone know: I will not be doing any more work on turpentine at all. I recently changed jobs and am no longer working with Magento. I hope @aheadley will get around to merging this soon.

**Comment by anderow** [comment]
Thanks for your  contributions anyway eth8505

**Comment by craigcarnell** [comment]
@aricwatson While your doing your recent merges into devel, perhaps look into this one? Thanks

**Comment by aricwatson** [comment]
FYI - will probably bump master to 0.6.2 today or tomorrow and then start working on this.

**Comment by craigcarnell** [comment]
@aricwatson Any updates on this? Thanks

**Comment by craigcarnell** [comment]
@aricwatson @miguelbalparda bump!

**Comment by aricwatson** [comment]
We're still working on it - more updates soon.

**Comment by aricwatson** [comment]
The *devel-varnish4* branch should be all current with the main *devel* branch, if anyone wants to test varnish4 with the current code. So far everything seems to be working well!

**Comment by aricwatson** [comment]
These changes have been merged into devel here https://github.com/nexcess/magento-turpentine/pull/883 - Big thanks to @eth8505 for all his work. Please keep testing using the devel branch and if all goes well this should be in the next version of Turpentine!

**Pull request closed without merging**
