### PR TITLE
Issue: #741 Custom module controller_action_layout_load_before 

### PR DESCRIPTION
**Pull request by NikolasMeyer**
This fix should resolve issue #741.

### CODE REVIEW

**Comment by NikolasMeyer** [comment]
It's about layout changed by a 3rd party module.
The Module has an EventObserver that adds a layout handle on "controller_action_layout_load_before". In this case we replace the top.search block from default handle. The result is, that we have to blocks with name "top.search" in the reference "header". The first one is the updated one from the module and the second is the block from default handle.
In Magento block-generation a block is overridden if another block with the same name is added. In my tests with some different modules the newer block was always the first one. If we reverse the array with the blocks, the newer block is processed later. The result is that the last added block is processed last.

Perhaps it is possible to detect on block level if this block is overridden by another block to prevent processing of unnecessary blocks. But I don't know any method to detect this on this level.

**Comment by miguelbalparda** [comment]
> In Magento block-generation a block is overridden if another block with the same name is added. In my tests with some different modules the newer block was always the first one. If we reverse the array with the blocks, the newer block is processed later. The result is that the last added block is processed last.
wouldn't this be 
>  If we reverse the array with the blocks, the newer block is processed instead of being not processed. The result is that the last added block is processed first.

**Comment by NikolasMeyer** [comment]
At the moment and with this fix all blocks are processed by magento. But only the last processed block generates an output. On line 257 we call the Magento function "generateBlocks" for each block in the updated layout. This results in a call to addBlock method on the layout. In this function magento retrieves the name from the block and adds the prepared block to an array..
$this->_blocks[<block_name>] = $block 
This array is processed to the output later.

Maybe you are right. It's possible that our layout handle is added before the default layout handle is loaded. But in fact in this case blocks get processed another way than magento does. After your comment I'm not really sure if we can rely on the order of the blocks in the layout. Perhaps you know another way to determine if we have to generate a block?

**Comment by miguelbalparda** [comment]
I'm not entirely sure about another way to do this, but you do have a point when you say the last generated block should be the one processed and not the first one as it is now and it seems your array_reverse idea might be helpful. There was another issue with this but I can't find it now.

**Comment by NikolasMeyer** [comment]
Perhaps you want to have a look on Pull Request #1263.

> I experienced that the layout XML for an ESI tag was loaded in a different order then default Magento loads it. This gave a different result.

I think this addresses the same issue but I have not checked if the solution solves my issue. If you think it's helpful I can deploy this patch to our system the next days and report my results.

**Comment by miguelbalparda** [comment]
Yeah that was probably the one. Can you check it and compare it with your results?

**Comment by NikolasMeyer** [comment]
Seems like it is working for me. But I want to investigate further tests before i approve this for production.
Further reports on Monday..

**Comment by NikolasMeyer** [comment]
@miguelbalparda Sorry for my delay. After a deployment of a rebased version of pull request #1263 everything works fine. In my opinion this is a good solution.

Can you estimate a time to finish your tests and for a merge?

**Comment by miguelbalparda** [comment]
Perfect then, I'll close this PR for now in favor of the other one. Thank you for the help!

**Pull request closed without merging**
