### PR TITLE
Add ability to manage pre and post custom VCL inclusions

### LINKED ISSUE #1083: Passing a subdomain via custom_include.vcl does not seem to work
I have added the following to _custom_include.vcl_:

sub vcl_recv {
	if (req.http.host ~ "staging") {
	   return (pass);
	}
}

This does not seem to work, as I am still getting hits when accessing the "staging" subdomain.

However, if I manually overwrite the Varnish configuration as generated by Turpentine and add my "_if_"-condition at the beginning of the existing "_vcl_recv_" subroutine, I am no longer getting any hits on the "staging" subdomain.

My question is this: Is it possible that my custom "_if_" condition is never executed because _custom_include.vcl_ is added at the very bottom of the VCL file as created by Turpentine?

### PR DESCRIPTION
**Pull request by bmalynovytch**
Handles 2 different custom_include.vcl (bottom) and custom_pre_include.vcl (top)
Fixes #1083

### CODE REVIEW

**Comment by miguelbalparda** [comment]
What is the difference between this PR and https://github.com/nexcess/magento-turpentine/pull/1096? @andrewkett

**Comment by bmalynovytch** [comment]
As far as I remember, quite none, the main idea being the same.
I found #1096 lately, mine was already opened.

My code is running fine in production and was reviewed by the main developper / maintainer on my customer's side.

**Comment by miguelbalparda** [comment]
This seems to be a useful feature, we have 3 PR with the same idea. Have you seen #1151?

**Comment by bmalynovytch** [comment]
Nope, I didn't have much time to review both of them.

**Comment by miguelbalparda** [comment]
We are going to use #1172 for now.

**Pull request closed without merging**
