### PR TITLE
Updated constant REGEXP_VARNISH_VERSION to identify Varnish versions …

### PR DESCRIPTION
**Pull request by notimplementedyet**
…with muliple mayor,minor,sub digits

### CODE REVIEW

**Comment by sprankhub** [comment]
:+1: please merge @miguelbalparda

**Comment by jonashrem** [comment]
+1

**Comment by miguelbalparda** [comment]
There is another PR touching this very same regex, can you check it please? #1502

**Comment by jonashrem** [comment]
Both PR are fixing the same issue @miguelbalparda 

This one is changing all three numbers to arbitrary numbers  so it works with Versions like 10.20.103 as well while #1502 is adding an optional second digit to the major version, so it matches with 4.1.10 but not 4.1.100.

To be save in case Varnish is ever changing version schema I suggest using this solution #1491

**Comment by miguelbalparda** [comment]
Gotcha @jonashrem, we'll go with this one. Thanks!!

**Pull request merged**
