### PR TITLE
Ban Observer - Fix an issue on ban product review

### PR DESCRIPTION
**Pull request by antoinekociuba**
Check if varnish is enabled was missing on banProductReview method (Nexcessnet_Turpentine_Model_Observer_Ban::banProductReview line 320)
+
Reformat code

### CODE REVIEW

**Comment by miguelbalparda** [comment]
@antoinekociuba fix seems to be correct, but the new syntax and the code reformatting is different from the one we are using here. Would you mind using the notation and style we are currently using in your files?

**Comment by antoinekociuba** [comment]
@miguelbalparda yeah sure, that's fine to me.

BTW, which syntax/code styling do you usually use? 

On my side, I'm using PHPStorm and I use PSR-1/PSR-2 Code arrangement, and in my opinion, it perfectly fits Magento coding standard.

Thx

**Comment by antoinekociuba** [comment]
Hi @miguelbalparda,

Syntax and code formatting are now same as they were before.
Only the missing condition has been added to ban observer model for this PR.

Regards

**Comment by miguelbalparda** [comment]
@antoinekociuba I just noticed this is pointing to master. Can you edit this and point the PR to devel?

**Pull request closed without merging**
