### PR TITLE
Add maintenance mode that will allow debug_ips through to visit the site, all other users get the landing page

### PR DESCRIPTION
**Pull request by craigcarnell**
Re-opening as I accidentally closed it...

Typically we want to take a store offline or put up a different holding page while we are doing maintenance. We can do this on our load balancer but at the moment this does not allow us to set a bespoke holding page.

What this does is allow us to create a bespoke holding page by editing the System->Config->Turpentine->Maintenance->VCL Synth which will get displayed to every one not maching the IP set in System->Config->Developer->Debug IPs

In VCL Synth you simply copy and paste your HTML into it.

This feature can be enabled or disabled via the setting Maintenance Mode Enabled Yes or No

All users outside this range will get the holding page without a backend fetch
All users matching the IP range will get the website.

You cannot do this with Magento - if you set the maintenance.flag everyone will get the holding page. If you use Varnish then this page then get's cached.

This gets around the issue for me.

This feature has been written to work on Varnish 3 and 4. I am using 4 primarily in my environment.

### CODE REVIEW

**Comment by miguelbalparda** [comment]
@craigcarnell we are debating on this PR. We think this is not something every user will need but some might find this useful. Maintaining this in upcoming releases is time consuming and that is why we are hesitating about merging this into devel and then into master.We think creating a branch for community contributions is the way to go, but we are not sure. Thoughts? + @aricwatson

**Comment by craigcarnell** [comment]
@miguelbalparda @aricwatson Fine with me! I imagine putting your site in maintenance mode occasionally for upgrades etc is always helpful to everyone

**Comment by miguelbalparda** [comment]
Thank you for your contribution @craigcarnell!

**Comment by svankik** [comment]
It work fine for one IP address but for multiples allowed IP => ip1,ip2,ip3

we must have in VCL :

acl debug_acl {
"ip1";
"ip2";
"ip3";
}

and not 

acl debug_acl {
"ip1,ip2,ip3";
}

and for the test :

if (req.http.X-Forwarded-For !~ "(ip1|ip2|ip3)") {
return (synth(999, "Maintenance mode"));
}

and not

if (req.http.X-Forwarded-For !~ "ip1,ip2,ip3") {
return (synth(999, "Maintenance mode"));
}

And why is the response status 404 in stead of 503 for Varnish 4 ?

**Comment by miguelbalparda** [comment]
@svankik feel free to create a PR with your modifications!

**Pull request merged**
