### PR TITLE
Fix the issue when redirect HTTP to HTTPS

### PR DESCRIPTION
**Pull request by hmphu**
I am using Varnish as front door listen on public IP & port 80, and using NGINX listen on port 80 for the backend, and 443 for HTTPS.

The issue is when I enter the HTTP URL with parameters it always redirects to home page. For example,  I enter http://example.com/about-us , it redirects to https://example.com 

The fix will keep the URL parameters when redirecting from HTTP to HTTPS. So when I enter http://example.com/about-us, it will redirect to https://example.com/about-us

Thanks to considering to check and merge.

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Can you point this to devel instead of master? Also, this seems to be pretty broad, do you think this will affect other users not using https/nginx in any way?

**Comment by hmphu** [comment]
Hi @miguelbalparda, 

Sorry for the mistake. I pointed this to the devel branch.

Other users who are not using https and don't have the similar issue like me can disable the option in admin configuration page. It is disabled by default. So I think it will not affect to other users.

Thanks,
Phu

**Comment by miguelbalparda** [comment]
@hmphu can you write a quick note I can introduce in the Wiki for this new feature please? I'd like to merge it once we have that.

**Comment by hmphu** [comment]
@miguelbalparda , thanks for your updates.


As you probably know, [Varnish doesn't support HTTPS](https://www.varnish-cache.org/docs/trunk/phk/ssl_again.html). 

So the solution is configure Nginx to listen to 443 port and work as an SSL proxy. Look at the illustration bellowm, I borrowed it from the article [HTTPS with Varnish](https://komelin.com/articles/https-varnish)

alt text

Step by step:

* A visitor attepts to the site over HTTPS protocol
* Nginx (SSL Proxy) will forwards the request to Vanish (Cache Proxy)
* Varnish will request content from backend (Nginx) if necessary and returrn back to Nginx (SSL proxy)
* Nginx (SSL Proxy) will send the content to the end-user

Configure Magento + Turpentine this way will caused a redirect problem: 

* A visitor enter the website url without https, eg: http://example.com/contact-us
* Nginx (SSL Proxy) will forwards the request to Varnish proxy
* Varnish will request content from backend. This time Magento detect the url is not HTTPS and redirect user to the homepage with https (https://example.com)
* Nginx send the page content to the end-user

My fix will create a sub vanish routine

```php
/*
* File: Nexcessnet/Turpentine/misc/version-3.vcl and /Nexcessnet/Turpentine/misc/version-4.vcl
*/

sub vcl_synth {
   if (resp.status == 750) {
        set resp.status = 301;
        set resp.http.Location = "https://" + req.http.host + req.url;
        return(deliver);
    }
}
```

and in `vcl_recv` subroutine, the code bellow will check the request uri and redirect to https uri if necessary.

```php
/*
* File: Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php
* Function: _vcl_sub_https_redirect_fix()
*/

$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
$baseUrl = str_replace(array('http://','https://'), '', $baseUrl);
$baseUrl = rtrim($baseUrl,'/');
```    

```php
/*
* File: Nexcessnet/Turpentine/misc/version-3.vcl and /Nexcessnet/Turpentine/misc/version-4.vcl
*/

if ( (req.http.host ~ "^(?i)www.$baseUrl" || req.http.host ~ "^(?i)$baseUrl") && req.http.X-Forwarded-Proto !~ "(?i)https") {
        return (synth(750, ""));
}
```

Please let me know what you think.

I'm verry happy to contribute to this great extension!!!

Thanks,
Phu

**Comment by miguelbalparda** [comment]
Thank you for your contribution @hmphu!

**Comment by miguelbalparda** [comment]
This PR seems to be causing #1312, can you take a look @hmphu?

**Comment by hmphu** [comment]
hi @miguelbalparda my FixHTTPSRedirect repo was changed so I cloned devel and create new PR #1315 instead

**Comment by hmphu** [comment]
also I though `{{vcl_synth}}` in `vesion-3.vcl` template will cause an error on Varnish v3 when you enable Maintenance Mode because v3 use `vcl_error` instead of `vcl_synth`. Please check that too

**Pull request merged**
