### PR TITLE
Add option to configure which customer group must have different cache content

### PR DESCRIPTION
**Pull request by Stasevi4**
Create option to select which groups of customers must have different content. issue #1051

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Sounds useful @Stasevi4, can you write a small text we can use for documenting/wiki this feature?

**Comment by Stasevi4** [comment]
# Customers Group Caching

- **Customer Group**: Allows you to specify customers group with different cache content.

**Comment by jeroenvermeulen** [comment]
Looks good (did not test it).
Only thing I am worried about is you seem to be changing the default behaviour, because none of the customer groups are selected by default.
This means if somebody upgrades the Turpentine extension, its behaviour in combination with customer groups changes. It will no longer split cache for customer groups, unless he updates the configuration.
Maybe it is possible to overcome this by adding an setup script in the `sql` dir? Although of course these scripts are meant to do DB changes.

**Comment by Stasevi4** [comment]
If we change 
``` if(!in_array($customer->getGroupId(), $customerGroups)) {
            return;
    }
```
to 
``` 
 if(!in_array($customer->getGroupId(), $customerGroups) && strlen($customerGroups[0]) > 0) {
           return;
 }
```
We can check if config is empty we will create cache for all groups if config has been changed from admin we will use rules to make cache for selected groups.

**Comment by jeroenvermeulen** [comment]
Good solution!

**Review by miguelbalparda — APPROVED** [review]

**Pull request merged**
