### PR TITLE
Fix: Handles order / Block generation

### PR DESCRIPTION
**Pull request by jasperzeinstra**
I experienced that the layout XML for an ESI tag was loaded in a different order then default Magento loads it. This gave a different result. I will explain in more detail below. I also changed the way the needed blocks are generated by using more standard Magento methods.

The event `controller_action_layout_load_before` was dispatched before the layout handles were added. `\Mage_Customer_Model_Observer::beforeLoadLayout` listens to this events and add the layout handel `customer_logged_(in|out)`. After this event has been dispatched the handles needed for the ESI block are added. But since `customer_logged_(in|out)` is already added it won't re-add this. Now when the XML is being generated the XML of that handle is loaded first. In my theme I remove some links from the `top.links` block. But these can't be removed since they are added later on in the XML.

I've fixed this problem by removing the dispatching of the event. Adding the handles by using the `addHandle` method. After adding the handles I load it by using the method `loadLayoutUpdates`, the method also fires the `controller_action_layout_load_before` event. And instead of dispatching the event `controller_action_layout_generate_xml_before` and using method `generateXml` I'm using the default Magento method `generateLayoutXml` which also dispatches the same event.

I also changed the generation of blocks. The default Magento method `generateLayoutBlocks` generates all block that doesn't have the attribute `ignore`. So instead of finding out what block i need to generate and not using default Magento methods. I set all the blocks that I don't want to generate to skip. And the I use the default Magento method `generateLayoutBlocks`

If you have any questions about this pull request feel free to ask.

Regards,
Jasper

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Have you checked #1164? @craigcarnell was working on it.

**Comment by jasperzeinstra** [comment]
No that issue didn't looked as the same bug i found. Also my pull request is doing something totally different.

**Comment by miguelbalparda** [comment]
@jasperzeinstra can you fix the conflicts so I can merge this with devel?

**Comment by miguelbalparda** [comment]
Can you check https://github.com/nexcess/magento-turpentine/pull/1301 and also resolve the conflicts?

**Comment by miguelbalparda** [comment]
Closing for lack of feedback, we'll go with #1516

**Pull request closed without merging**
