### PR TITLE
Fix for dummy blocks not working

### LINKED ISSUE #473: can't flush topline block in cache
Hi, I'm having an issue flushing a "topline" block in cache.
Using Turpentine 0.6.0, Varnish 3 and Magento 1.8. All works fine, excluding the topline block located in root reference in my custom template. Issue reproduces as follows:
- when user logs in and browses to any cached page, topline block shows no login
- when user logs out and browses to a cached page, the opposite happens, topline shows that user is still logged in.
Here's the relevant part of the /app/design/frontend/theme/layout/local.xml:
```
<reference name="root">
            <reference name="root">
                <action method="setTemplate"><template>page/2columns-left.phtml</template></action>
            </reference>
            <!--<remove name="left"></remove>-->

            <block type="page/html_notices" name="global_notices" as="global_notices" template="page/html/notices.phtml" />
            <block type="core/messages" name="global_messages" as="global_messages"/>
            <block type="core/messages" name="messages" as="messages"/>

			<!-- top login -->
            <block type="core/template" name="topline" as="topline" template="custom/topline.phtml">
	            <action method="insert">
	                <block_name_to_insert>top.links</block_name_to_insert>
	                <sort_relative_to_other_childname/>
	                <sort_before_or_after/>
	                <alias>topLinks</alias>
	            </action>
            
                <block type="page/switch" name="store_language" as="store_language"
                       template="page/switch/languages.phtml"/>
                <block type="directory/currency" name="currency_top" template="page/switch/currency.phtml"/>
                <block type="customer/form_login" name="mini_login" template="customer/form/mini.login.phtml"/>
                <block type="core/template" name="socialogin" as="socialogin" template="customer/socialogin.phtml"></block>
                <block type="buyshopconfig/twitter" name="twitter_last_feed" as="twitter_last_feed" template="twitter/twitter_last_feed.phtml"/>v
            </block>
```

I tried to cause the topline block to be flushed in cache by adding a following to turpentine_esi.xml:
```
<reference name="topline">
<block type="customer/form_login" name="mini_login" template="customer/form/mini.login.phtml"/>
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <method>esi</method>
        </params>
    </action>
</block>
</reference>
```

I tried different options, switching method to ajax, setting ttl 0, dimmy_block head, dummy_block root.... But it makes no difference, just like the block is not parsed in turpentine_esi.xml.
If I add the "setEsiOptions" to my theme's local.xml, the topline block fails to load.
I need either to flush this block from cache, or exclude it from caching, doesn't matter.
Please advise.
Thanks in advance.

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
Dependent of the version of SimpleXML, on some systems the names of the `<dummy_blocks>` were put in the keys instead of the values of `$esiOptions['dummy_blocks']`.
This caused them not to work.
My solution may fix #473 and #178. Of cause you still need to use the `<dummy_blocks>` in the right way, but previously the dummy blocks may not have worked on particular systems

### CODE REVIEW

**Comment by aricwatson** [comment]
This has been merged into the *devel* branch and will be in the next release, pending testing. Thanks!

**Comment by jeroenvermeulen** [comment]
Great to notice the Turpentine project is being actively developed again!

**Comment by aricwatson** [comment]
Thanks - and thanks for being patient!

**Comment by nicka101** [comment]
I can confirm that this fixes issues with dummy_blocks on multiple sites I manage

**Pull request closed without merging**
