### PR TITLE
Fix messages returning a empty <ul />

### PR DESCRIPTION
**Pull request by BarryCarlyon**
As requested in https://github.com/nexcess/magento-turpentine/pull/814#issuecomment-114934759 reopening at devel instead of master

### CODE REVIEW

**Comment by miguelbalparda** [comment]
@BarryCarlyon can you give us a step by step guide to reproduce the issue you were experiencing?

**Comment by BarryCarlyon** [comment]
There are no steps.

I was getting a <ul></ul> for no reason, I traced the issue back to turpentine, as the block hinter was saying it was a turp's block.

Changed the code in this PR and boom no empty <ul></ul> anymore

**Comment by craigcarnell** [comment]
Code seems logical to me :+1:

**Comment by miguelbalparda** [comment]
Thank you for your contribution @BarryCarlyon!

**Pull request merged**
