### PR TITLE
Feature: Custom file include on top of VLC

### PR DESCRIPTION
**Pull request by jeroenvermeulen**
When multiple subroutines with the same name exist in Varnish, they get concatenated.
The existing 'custom_include.vcl' file is appended to the VCL. It can't be used to expand the 'sub vcl_recv' because the existing one contains 'return (pipe)' statements. Whatever you add will not be executed in a lot of situations.
I added a 'custom_include_top.vcl' file, which is prepended to the VCL. This allows you to override everything. For example you can include a 'return (pipe)' yourself to skip the default Turpentine VCL :-)

### CODE REVIEW

**Comment by miguelbalparda** [comment]
#1096 #1151 and #1134 are exactly the same feature with different approaches. Thoughts @jeroenvermeulen?

**Comment by jeroenvermeulen** [comment]
@miguelbalparda 
#1096 is not backwards compatible, because the config path is changed.
#1151 and #1134 look OK
However I think mine is best because it uses a generic and backwards compatible function `_getCustomIncludeFilename` and some `for` loops to keep things efficient and future-proof for more VCL include locations.

**Comment by jeroenvermeulen** [comment]
My implementation is running live on the site https://www.outdoorxl.nl/

**Comment by jeroenvermeulen** [comment]
Just used my PR for another customer's live site, Varnish 4: https://www.snowcountry.nl/
I have improved it a little and made it up-to-date with the `devel` branch. 
@aricwatson Can you merge my PR?

**Comment by miguelbalparda** [comment]
Thank you for your contribution @craigcarnell and sorry for the delay.

**Comment by jeroenvermeulen** [comment]
@miguelbalparda You're welcome, say hi to @aricwatson

**Pull request merged**
