### PR TITLE
Support PHP7

### PR DESCRIPTION
**Pull request by allardhoeve**

### CODE REVIEW

**Comment by vdloo** [comment]
:+1: php7cc shows no apparent issues. 

would presumably fix the following error in the connect manager:

```
Checking dependencies of packages

CONNECT ERROR: Package community/Nexcessnet_Turpentine 0.6.8: requires PHP version >= 5.2.13 and <= 6.0.0 current is: 7.0.4
```

**Comment by miguelbalparda** [comment]
@allardhoeve can you point this PR to devel instead of master? Thank you!

**Comment by WesMage** [comment]
@miguelbalparda Is the extension now php7 compatible?

**Comment by miguelbalparda** [comment]
@WesMage yes, we will be releasing a new version on Magento Connect in a week or so. In the meantime, feel free to use the devel branch of this repo.

**Pull request closed without merging**
