### PR TITLE
added ESI options for contact form, #116, #486

### PR DESCRIPTION
**Pull request by sprankhub**
This ensures that no user data is stored in Varnish (the contact form is pre-filled with user data for logged in users).

### CODE REVIEW

**Comment by miguelbalparda** [comment]
I'm trying to catch up with the PRs, can you point this to devel instead of master? Sorry for the delay!

**Comment by sprankhub** [comment]
Thanks @miguelbalparda! Done.

**Comment by sprankhub** [comment]
BTW: You may want to set the base branch of the repository to devel to have fewer PRs to master.

**Comment by sprankhub** [comment]
It turned out that wholepunching the `contactForm` block was not enough. The form action was only `post` in this case and not the whole shop URL plus `contacts/index/post`. I now excluded the whole contacts page, which seems to work.

**Pull request merged**
