### PR TITLE
Fix varnish version matching regex

### PR DESCRIPTION
**Pull request by lrauldan**
Update the regular expression to match patch versions higher than 9.

### CODE REVIEW

**Comment by lrauldan** [comment]
We have discovered this bug while trying to use varnish 4.1.10 in our environment.

**Comment by miguelbalparda** [comment]
I'll need you to edit this PR and point it to devel instead of master to be merged.

**Comment by miguelbalparda** [comment]
There is another PR touching this very same regex, can you check it please? #1491

**Comment by miguelbalparda** [comment]
We'll go with #1491, thanks a lot for your help!!!

**Pull request closed without merging**
